### ISSUE TITLE
Add ranking system for messages

### ISSUE THREAD

**Issue by ParisNeo** [nomic-ai/gpt4all-ui#10]
Hi there.
Is anyone interested in adding a vote up, vote down ranking system to the ui and db?
That would help fine tuning afterwards.

**Comment by mkinney** [comment]
Perhaps add "good first" and "enhancement" labels?

**Comment by ParisNeo** [comment]
ok. Do you want me to assign this issue to you?

**Comment by mkinney** [comment]
I'd like to get it working first before committing to this issue.

**Comment by ParisNeo** [comment]
perfect

**Comment by ParisNeo** [comment]
Hi there. I have already integrated ranking system. You may want to enhance it. Start from the last version if you please.

**Comment by andzejsp** [comment]
this is implemented, so you can close this issue
