### ISSUE TITLE
Models now showing in menu after restart

### ISSUE THREAD

**Issue by nikben** [nomic-ai/gpt4all-ui#102]
## Expected Behavior
Please describe the behavior you are expecting.
In "Settings" the "model" menu should show all models downloaded, shown in second screenshot.
Initially, it worked as expected.

## Current Behavior
Please describe the behavior you are currently experiencing.
In "Settings" the "model" menu is empty, as seen in the third screenshot.
This happened after a reboot to add more memory to the PC.

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. Step 1: Stop the webui.sh script.
2. Step 2: Start the webui.sh script.

## Possible Solution
If you have any suggestions on how to fix the issue, please describe them here.
None found.

## Context
Please provide any additional context about the issue.
OS: Ubuntu 22.04.2 LTS
Stopped webui.sh script, deleted both models, copied just one (gpt4all-lora-quantized-ggml.bin) and started webui.sh with the result shown in first screenshot.
Model is found and skipped for download, but is not found later on.
If I try to change settings, I get a message that everything was successful, although no model is selected.

As a result, GPT4all does not respond at all. 

## Screenshots
If applicable, add screenshots to help explain the issue.

![image](https://user-images.githubusercontent.com/21334682/233334849-bbc3ebf1-c78e-4c48-90d0-6893234dbdf6.png)
![image](https://user-images.githubusercontent.com/21334682/233335055-23b0d027-bbdd-4817-bfaa-e0aa4b2fcf0d.png)
![image](https://user-images.githubusercontent.com/21334682/233336093-98d8860a-58b9-4f30-88fe-e4714d140857.png)
![image](https://user-images.githubusercontent.com/21334682/233336587-954cbf65-2026-4cc6-b597-89795866ea25.png)

**Comment by cmdrscotty** [comment]
I'm also getting this on the windows version as well.

i can see in the console that it does indeed load the model, but fails to actually use it, and the settings page shows nothing to select. Just did a git clone to get the latest version as well

`llama_model_load: loading model from './models/llamacpp/gpt4all-lora-quantized-ggml.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 4096
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 32
llama_model_load: n_layer = 32
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 11008
llama_model_load: n_parts = 1
llama_model_load: type    = 1
llama_model_load: ggml map size = 4017.70 MB
llama_model_load: ggml ctx size =  81.25 KB
llama_model_load: mem required  = 5809.78 MB (+ 2052.00 MB per state)
llama_model_load: loading tensors from './models/llamacpp/gpt4all-lora-quantized-ggml.bin'
llama_model_load: model size =  4017.27 MB / num tensors = 291
llama_init_from_file: kv self size  =  512.00 MB
[2023-04-20 11:11:24,622] {_internal.py:224} INFO - 127.0.0.1 - - [20/Apr/2023 11:11:24] "GET /list_discussions HTTP/1.1" 200 -
[2023-04-20 11:11:30,086] {_internal.py:224} INFO - 127.0.0.1 - - [20/Apr/2023 11:11:30] "←[36mGET /static/images/copy.png HTTP/1.1←[0m" 304 -
[2023-04-20 11:11:30,087] {_internal.py:224} INFO - 127.0.0.1 - - [20/Apr/2023 11:11:30] "←[36mGET /static/images/refresh.png HTTP/1.1←[0m" 304 -
[2023-04-20 11:11:30,087] {_internal.py:224} INFO - 127.0.0.1 - - [20/Apr/2023 11:11:30] "←[36mGET /static/images/thumb_up.png HTTP/1.1←[0m" 304 -
[2023-04-20 11:11:30,088] {_internal.py:224} INFO - 127.0.0.1 - - [20/Apr/2023 11:11:30] "←[36mGET /static/images/thumb_down.png HTTP/1.1←[0m" 304 -`

![image](https://user-images.githubusercontent.com/36492195/233452512-1941ab46-931d-4239-8168-df67e323bf47.png)

**Comment by ParisNeo** [comment]
Hi there, can you test this: on the page, right click and press inspect then in the menue ui that apears select console and take a screenshot

**Comment by ParisNeo** [comment]
i think that you don't have the right structure. Can you do a pull request. i have made a little modification that should repare this.

**Comment by cmdrscotty** [comment]
ok did a pull which updated a few files and ran it again, I can still see in the command prompt console that it's loading the weights from the model

but the UI doesn't behave as it if loaded them, and settings page doesn't show anything that can be selected.

Console view in browser (tried Opera GX (chromium) and FireFox) both show this 
![image](https://user-images.githubusercontent.com/36492195/233502937-f44ee7da-b228-4b3d-9eae-d2415c11118c.png)

**Comment by ParisNeo** [comment]
Which browser are you using?

**Comment by ParisNeo** [comment]
This should have been resolved in last version
