### ISSUE TITLE
"Exception 'LLAMACPP' object is not callable" error on Ubuntu Linux

### ISSUE THREAD

**Issue by HughWilliams** [nomic-ai/gpt4all-ui#110]
## Expected Behavior

On macOS GPT4ALL - WEBUI  successfully starts and can ask questions and get responses:

Checking discussions database...
llama_model_load: loading model from './models/llama_cpp/gpt4all-lora-quantized-ggml.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 4096
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 32
llama_model_load: n_layer = 32
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 11008
llama_model_load: n_parts = 1
llama_model_load: type    = 1
llama_model_load: ggml map size = 4017.70 MB
llama_model_load: ggml ctx size =  81.25 KB
llama_model_load: mem required  = 5809.78 MB (+ 2052.00 MB per state)
llama_model_load: loading tensors from './models/llama_cpp/gpt4all-lora-quantized-ggml.bin'
llama_model_load: model size =  4017.27 MB / num tensors = 291
llama_init_from_file: kv self size  =  512.00 MB
Chatbot created successfully
 * Serving Flask app 'GPT4All-WebUI'
 * Debug mode: off
[2023-04-23 17:24:44,837] {_internal.py:224} INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:9600

## Current Behavior

On Ubuntu Linux GPT4ALL - WEBUI  successfully starts but when I ask questions and no responses are returned.

In the startup log I note the error "Exception 'LLAMACPP' object is not callable" on startup:

Checking discussions database...
llama_model_load: loading model from './models/llama_cpp/gpt4all-lora-quantized-ggml.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 4096
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 32
llama_model_load: n_layer = 32
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 11008
llama_model_load: n_parts = 1
llama_model_load: type    = 1
llama_model_load: ggml map size = 4017.70 MB
llama_model_load: ggml ctx size =  81.25 KB
llama_model_load: mem required  = 5809.78 MB (+ 2052.00 MB per state)
llama_model_load: loading tensors from './models/llama_cpp/gpt4all-lora-quantized-ggml.bin'
llama_model_load: model size =  4017.27 MB / num tensors = 291
llama_init_from_file: kv self size  =  512.00 MB
**Exception 'LLAMACPP' object is not callable**
Chatbot created successfully
 * Serving Flask app 'GPT4All-WebUI'
 * Debug mode: off
[2023-04-23 21:15:01,463] {_internal.py:224} INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9600
 * Running on http://172.30.0.77:9600
[2023-04-23 21:15:01,463] {_internal.py:224} INFO - Press CTRL+C to quit

I also not that when as part of the installation process I download the "gpt4all-lora-quantized-ggml.bin" file:

File ./models/llama_cpp/gpt4all-lora-quantized-ggml.bin does not exist.
What would you like to do?
1) Download		   3) Skip
2) Download using browser
#? 1

but it place in "./models" rather than "./models/llama_cpp" , which I have to manually copy it to. Although note I did the same thing on macOS and it worked !!!

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

Following the steps at:

     https://github.com/nomic-ai/gpt4all-ui#linux
     
or at:

    https://github.com/nomic-ai/gpt4all-ui#manual-advanced-mode-1

**Comment by ParisNeo** [comment]
Hi there. Can you try the last version ?

**Comment by HughWilliams** [comment]
Try the last version of what, as I cloned the git archive yesterday ?

Please provide a link to what you want me to try if available ...

**Comment by ParisNeo** [comment]
the code moves at a high speed. Many things have changed last night as I was upgrading the whole system.
To install the tool, look at my video :
https://www.youtube.com/watch?v=M7NFajCyZKs&lc=UgxGg67y1jObxCPTq7Z4AaABAg

**Comment by ParisNeo** [comment]
Ah, I am soory, I didn't test it on ubuntu but I'll do that tomorrow as I have access to an ubuntu machine
For now, I am mainly coding on windows. There are many upgrades that I'm doing at the same time everywhere in the code. Since I am coding this alone, it takes time. Sorry for that

**Comment by HughWilliams** [comment]
OK, let me know your outcome from testing on Ubuntu ...

**Comment by HughWilliams** [comment]
Is the issue running slow on Ubuntu suppose to have been fixed, as I cloned the git repo again and still having the same problem ?
