### ISSUE TITLE
Change download destination of model to './models/llama_cpp/gpt4all-lora-quantized-ggml.bin'

### ISSUE THREAD

**Issue by funwithforks** [nomic-ai/gpt4all-ui#114]
### Expected Behavior
The gpt4all-ui linux installation should be completed without any issues.

### Current Behavior
When running the installation using the provided command, the gpt4all-ui linux exits and does not install. This is because it cannot find the downloaded model.

### Steps to Reproduce
To reproduce the issue, follow these steps:
1. Create a directory for gpt4all-ui using the command: `mkdir -p ~/gpt4all-ui`
2. Download webui.sh using the command: `curl -L https://raw.githubusercontent.com/nomic-ai/gpt4all-ui/main/webui.sh -o ~/gpt4all-ui/webui.sh`
3. Give execution permissions to webui.sh using the command: `chmod +x ~/gpt4all-ui/webui.sh`
4. Move to the gpt4all-ui directory using the command: `cd ~/gpt4all-ui`
5. Run webui.sh using the command: `./webui.sh`

### Possible Solution
The issue is caused because the downloaded model is located in the `./models/gpt4all-lora-quantized-ggml.bin` directory, while the script checks for it in `./models/llama_cpp/gpt4all-lora-quantized-ggml.bin`. This can be fixed by modifying line 133 of the downloaded webui.sh file as follows:

Change:
```
wget "$MODEL_URL" -P ./models/
```
to:
```
wget "$MODEL_URL" -P ./models/llama_cpp/
```

Alternatively, the download destination could be changed to the correct directory.

### Context
This issue is specific to the gpt4all-ui linux installation and is caused by a mismatch between the download location and the location that the script checks for the downloaded model.

### Screenshots
No screenshots are provided for this issue.

**Comment by ebarkhordar** [comment]
The same!

**Comment by ParisNeo** [comment]
Problem fixed
