### ISSUE TITLE
Duplicate responses!

### ISSUE THREAD

**Issue by ebarkhordar** [nomic-ai/gpt4all-ui#115]
<img width="705" alt="image" src="https://user-images.githubusercontent.com/22658149/234156606-304189a9-3f29-4efa-a6bd-052672a27282.png">

I just got this when I was trying to work with the model.

**Comment by ParisNeo** [comment]
No, this is not normal. What model are you using and can you test again with the latest version?
The new code (from few hours ago) forbids the model from halucinating the user text. So if this is happening, either you are using an old version or something is odd with the model.
