### ISSUE TITLE
docker compose  build failed: ERROR [internal] load metadata for docker.io/library/python:3.10 

### ISSUE THREAD

**Issue by g1thubX** [nomic-ai/gpt4all-ui#116]
```docker compose -f docker-compose.yml build```

I use the above command to prompt the following error, how can I solve it?
## Screenshots
![image](https://user-images.githubusercontent.com/118092383/234173629-f56847d8-459e-48d4-a3d4-f047a3dbc0c2.png)

**Comment by ParisNeo** [comment]
that's bizarre, as the templates folder does exist in the repo!

**Comment by g1thubX** [comment]
templates I solved it by re-pulling the file. Is the above python problem caused by the network failure?

**Comment by ParisNeo** [comment]
Maybe. I don't know what hapened. The most important thing is that you have managed to make it work.
Thanks for testing the tool.
