### ISSUE TITLE
Run GPT4All in Google Colab

### ISSUE THREAD

**Issue by MyEcoria** [nomic-ai/gpt4all-ui#118]
I created a notebook to launch this project in Google colab and to be able to access the site from the outside thanks to Localtunnel

[Open In Google Colab](https://colab.research.google.com/drive/1irqU4Af5T8nQ9NNCBGiZ_-rPG3AW-NlV#scrollTo=5VRlytgscthQ) 

[Download the notebook file for Google colab](https://github.com/MyEcoria/gpt4all-ui-colab/releases/download/V1.0/ChatGptAll-Ui.ipynb)

**Comment by ParisNeo** [comment]
sweet? Do you want to share your work in the project? You can fork the project, add a folder notebooks, put your notebook, then do a pull request.
