### ISSUE TITLE
Suggest modify to show progressive typing with code modified as below

### ISSUE THREAD

**Issue by chongy076** [nomic-ai/gpt4all-ui#132]
## Expected Behavior
Show realtime characters appear on chat progressively.

![image](https://user-images.githubusercontent.com/50088438/235279638-1cc82727-d7ab-4c52-bb81-22ee1b12ac10.png)

## Current Behavior
Show percentage inclusive of previous chat and current and appear full text when done.

## Possible Solution
If you have any suggestions on how to fix the issue, please describe them here.

[in folder pyGpt4All Api.py]
-----------------------------

    def new_text_callback(self, text: str):
        if self.cancel_gen:
            return False
        print(text, end="")
        sys.stdout.flush()
        
        if self.chatbot_bindings.inline:
            self.bot_says += text
            if not self.personality["user_message_prefix"].lower() in self.bot_says.lower():
                self.socketio.emit('message', {'data': self.bot_says});
                if self.cancel_gen:
                    print("Generation canceled")
                    return False
                else:
                    return True
            else:
                self.bot_says = self.remove_text_from_string(self.bot_says, self.personality["user_message_prefix"].lower())
                print("The model is halucinating")
                self.socketio.emit('final', {'data': self.bot_says})
                return False
        else:
            self.full_text += text
            if self.is_bot_text_started:
                self.bot_says += text
                if not self.personality["user_message_prefix"].lower() in self.bot_says.lower():
                    self.socketio.emit('message', {'data': self.bot_says});
                    #self.socketio.emit('message', {'data': text});
                    if self.cancel_gen:
                        print("Generation canceled")
                        self.socketio.emit('final', {'data': self.bot_says})
                        return False
                    else:
                        return True
                else:
                    self.bot_says = self.remove_text_from_string(self.bot_says, self.personality["user_message_prefix"].lower())
                    print("The model is halucinating")
                    self.socketio.emit('final', {'data': self.bot_says})
                    self.cancel_gen=True
                    return False
           
            #chong modified display realtime.      
            #if self.current_message in self.full_text:
            if len(self.discussion_messages) < len(self.full_text):
                self.is_bot_text_started = True
            else:
                #self.socketio.emit('waiter', {'wait': (len(self.discussion_messages)-len(self.full_text))/len(self.discussion_messages)})
                skeyword=self.personality["ai_message_prefix"]# "### Assistant:"
                ekeyword=self.personality["user_message_prefix"] # "### Human:"
                substring="" 
                sidx = self.discussion_messages.rfind(skeyword)
                eidx = self.discussion_messages.rfind(ekeyword)
                if sidx != -1:
                     substring = self.discussion_messages[sidx+len(skeyword):]
                elif sidx !=-1 and eidx !=-1 and eidx > sidx :
                     substring = self.discussion_messages[sidx+len(skeyword):sidx+len(skeyword)+eidx]
                else:
                     substring  (len(self.discussion_messages)-len(self.full_text))/len(self.discussion_messages)

                self.socketio.emit('waiter', {'wait': substring})

---------------------------------------------------------------------

[in main.js]

  socket.on('waiter', function(msg) {
    //chong modified
    //globals.bot_msg.messageTextElement.innerHTML    = `Remaining words ${Math.floor(msg.wait * 100)}%`;    
    globals.bot_msg.messageTextElement.innerHTML    = msg.wait;    
  });

**Comment by ParisNeo** [comment]
Thanks for your suggestion. Actually this is all a temporary solution. I am migrating the backend to a new form that doesn't spit the previous words before starting the response. So It will be faster and I'll be removing this all together. Yesterday I was too tired to work on this but I'l do it today.

Keep posted. And thanks for your suggestions, You are welcome to help. I'm doing this project for the people and I welcome any help.

**Comment by chongy076** [comment]
this is seem to be a good project.

**Comment by chongy076** [comment]
> Thanks for your suggestion. Actually this is all a temporary solution. I am migrating the backend to a new form that doesn't spit the previous words before starting the response. So It will be faster and I'll be removing this all together. Yesterday I was too tired to work on this but I'l do it today.
> 
> Keep posted. And thanks for your suggestions, You are welcome to help. I'm doing this project for the people and I welcome any help.

Hi , yes. I notice. The previous message was repost to API to reprocess previous msg for AI to know the previous conversation via client repost message. seem not ideal. But if load from the db from api end would be much more faster.
