### ISSUE TITLE
File ./models/llama_cpp/gpt4all-lora-quantized-ggml.bin not found!

### ISSUE THREAD

**Issue by Karenina-na** [nomic-ai/gpt4all-ui#134]
## Expected Behavior
I executed the webui.bat script but encountered an error

environment
windows 11
python 3.10

I also downloaded the model gpt4all la quantized.bin, where should I put it in the folder.

## Current Behavior
Checking internet connection
Internet connection not available
Virtual environment created and packages installed successfully.
Launching application...
Checking discussions database...
Traceback (most recent call last):
  File "W:\AI\gpt4all-ui\app.py", line 610, in <module>
    bot = Gpt4AllWebUI(app, socketio, config, personality, config_file_path)
  File "W:\AI\gpt4all-ui\app.py", line 60, in __init__
    super().__init__(config, personality, config_file_path)
  File "W:\AI\gpt4all-ui\pyGpt4All\api.py", line 50, in __init__
    self.chatbot_bindings = self.create_chatbot()
  File "W:\AI\gpt4all-ui\pyGpt4All\api.py", line 91, in create_chatbot
    return self.backend(self.config)
  File "W:\AI\gpt4all-ui\backends\llama_cpp\__init__.py", line 32, in __init__
    self.model = Model(
  File "W:\env\python\lib\site-packages\pyllamacpp\model.py", line 63, in __init__
    raise Exception(f"File {ggml_model} not found!")
Exception: File ./models/llama_cpp/gpt4all-lora-quantized-ggml.bin not found!

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. Step 1
2. Step 2
3. Step 3

## Possible Solution
If you have any suggestions on how to fix the issue, please describe them here.

## Context
Please provide any additional context about the issue.

## Screenshots
If applicable, add screenshots to help explain the issue.

**Comment by ParisNeo** [comment]
As shown in the error. Judt put it in models/llama_cpp folder.

**Comment by Karenina-na** [comment]
> 
Should I put gpt4all-lora-quantized-ggml.bin in the folder or gpt4all-lora-quantized.bin? I don't have the gpt4all-lora-quantized-ggml.bin file.

**Comment by Karenina-na** [comment]
> As shown in the error. Judt put it in models/llama_cpp folder.

I have already done so, but the program keeps getting stuck on this interface.

Checking internet connection
Internet connection not available
Virtual environment created and packages installed successfully.
Launching application...
Checking discussions database...
llama_model_load: loading model from './models/llama_cpp/gpt4all-lora-quantized-ggml.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 4096
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 32
llama_model_load: n_layer = 32
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 11008
llama_model_load: n_parts = 1
llama_model_load: type    = 1
llama_model_load: ggml map size = 4017.70 MB
llama_model_load: ggml ctx size =  81.25 KB
llama_model_load: mem required  = 5809.78 MB (+ 2052.00 MB per state)
llama_model_load: loading tensors from './models/llama_cpp/gpt4all-lora-quantized-ggml.bin'
llama_model_load: model size =  4017.27 MB / num tensors = 291
llama_init_from_file: kv self size  =  512.00 MB
Chatbot created successfully

**Comment by ParisNeo** [comment]
That's cool. Now just go to your browser and type: localhost:9600 and you should see the magic :)

**Comment by Karenina-na** [comment]
> That's cool. Now just go to your browser and type: localhost:9600 and you should see the magic :)

Thanks!
