### ISSUE TITLE
The replied from chat, continue run and show all the sample response

### ISSUE THREAD

**Issue by chongy076** [nomic-ai/gpt4all-ui#137]
## Expected Behavior
Show stop generating from sample and removed from replied message to user.

## Current Behavior
it is continue generating and 

![image](https://user-images.githubusercontent.com/50088438/235442082-d5689396-575a-4e0e-84e2-1fb13bbb1953.png)

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. Step 1 - load model ggml-vicuna-13b-4bit-rev1.bin
2. Step 2- start the chat 

## Possible Solution
The new committed code at the 8 hours ago was working fine also generate faster, and the latest  code seem removed many heavy code, 
May need to  take a look at from pyllamacpp.model import Model for code generation , previously was using self.cancel_gen=True to stop the generation. but notice , at the backend it is still running even cancel was called.

But at least on front end code stopped the hallucinations code from appeared at user end. 
The best would be at stop in model generation itself. it loaded large result which not required and consumed a lot of time,
unless the generation was broken into batched. otherwise the return may not able to stop the thread in the model.
        for tok in self.model.generate(prompt, 
                                           n_predict=n_predict,                                           
                                            temp=self.config['temp'],
                                            top_k=self.config['top_k'],
                                            top_p=self.config['top_p'],
                                            repeat_penalty=self.config['repeat_penalty'],
                                            repeat_last_n = self.config['repeat_last_n'],
                                            n_threads=self.config['n_threads'],
                                           ):
                if not new_text_callback(tok):
                    return

## Context
Please provide any additional context about the issue.

## Screenshots
If applicable, add screenshots to help explain the issue.

**Comment by ParisNeo** [comment]
The last version does stop every thing if you use the llamacpp backend. you have to update the project so that it installs the latest version of the backend requirements. pip install -r requirements.txt

**Comment by chongy076** [comment]
> The last version does stop every thing if you use the llamacpp backend. you have to update the project so that it installs the latest version of the backend requirements. pip install -r requirements.txt

Hi , i will try again.  At the same time. I am looking at pyllamacpp. it has the antiprompt, and some other parameters.
could you check the pull i did today, the code you updated on wsgi server, to run smoothly it can http_server can serve directly without needed to use socketio,run.
