### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by ParisNeo** [nomic-ai/gpt4all-ui#15]
The readme.me should be updated to give a better project description with better organieation.

**Comment by LiamorLG** [comment]
and make it even more noob friendly by explaining what navigate to the directory means cos i'm this terrible:

[liam@fedora openai-quickstart-node]$ cd GPT4All-ui
bash: cd: GPT4All-ui: No such file or directory
[liam@fedora openai-quickstart-node]$ run.sh
bash: run.sh: command not found...
[liam@fedora openai-quickstart-node]$ cd GPT4All-ui
bash: cd: GPT4All-ui: No such file or directory
[liam@fedora openai-quickstart-node]$

**Comment by ParisNeo** [comment]
No you are not terrible, my bad:
In linux, folders are case sensitive which means that :
gpt4all-ui is different from GPT4All-ui

So it was a mistake in the README.md and I just fixed it.

Thank you for the remark.

**Comment by LiamorLG** [comment]
and for my next stroke of genius: [liam@fedora gpt4all-ui]$ ./install.sh
bash: ./install.sh: Permission denied

**Comment by ParisNeo** [comment]
Can you make it executable by doing:
```
[liam@fedora gpt4all-ui]$ sudo chmod +x install.sh
```
I coded most of the stuff blindly since I am using Windows but people did make it work fine.

When we commit the file from windows, the executable flag is not added and so you have two ways:

- use the bash command to execute the code:
```
[liam@fedora gpt4all-ui]$ bash install.sh
```
- convert it to an executable then execute:
```
[liam@fedora gpt4all-ui]$ sudo chmod +x install.sh
[liam@fedora gpt4all-ui]$ ./ install.sh
```

**Comment by LiamorLG** [comment]
bash install.sh ftw :)

**Comment by ParisNeo** [comment]
Ubuntu is better than Fedora these days.

**Comment by LiamorLG** [comment]
thanks, any particular flavour for a noob with an old computer?

**Comment by ParisNeo** [comment]
Not really. You can take the latest LTS version of Ubuntu with Gnome desktop environment. I think the latest is 22.04LTS.
