### ISSUE TITLE
Error when starting: "llama_init_from_file: failed to load model"

### ISSUE THREAD

**Issue by mkinney** [nomic-ai/gpt4all-ui#18]
I'm getting an error when starting:

```
(venv) sweet gpt4all-ui % python app.py
llama_model_load: loading model from './models/gpt4all-lora-quantized-ggml.bin' - please wait ...
./models/gpt4all-lora-quantized-ggml.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])
	you most likely need to regenerate your ggml files
	the benefit is you'll get 10-100x faster load times
	see https://github.com/ggerganov/llama.cpp/issues/91
	use convert-pth-to-ggml.py to regenerate from original pth
	use migrate-ggml-2023-03-30-pr613.py if you deleted originals
llama_init_from_file: failed to load model
Checking discussions database...
Ok
llama_generate: seed = 1680843169

system_info: n_threads = 8 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
zsh: segmentation fault  python app.py
```

I have validated the md5sum matches:

```
sweet gpt4all-ui % md5sum models/gpt4all-lora-quantized-ggml.bin
387eeb7cba52aaa278ebc2fe386649b1  models/gpt4all-lora-quantized-ggml.bin
sweet gpt4all-ui % cat models/gpt4all-lora-quantized-ggml.bin.md5
387eeb7cba52aaa278ebc2fe386649b1
```

**Comment by rafatzbr** [comment]
Same error here.

**Comment by mkinney** [comment]
I should add I'm on an intel mac. The gpt4all chat's `gpt4all-lora-quantized-OSX-intel` works for me.

**Comment by rafatzbr** [comment]
I'm running on Linux. Also was able to run gpt4all-lora-quantized-Linux-x86

**Comment by rafatzbr** [comment]
I also tried to run this code:

`
from pyllamacpp.model import Model

def new_text_callback(text: str):
    print(text, end="")

model = Model(ggml_model='./models/gpt4all-lora-quantized-ggml.bin', n_ctx=512)
model.generate("Once upon a time, ", n_predict=55, new_text_callback=new_text_callback, n_threads=8)
`

and got the same error, which points to an invalid file.

**Comment by ParisNeo** [comment]
Yes you are right. The model provided by Nomic-ai is not compatible with windows. I'll ask them to provide a working version soon.

In the meanwhile you can download the model and convert it by yourself as presented in:
https://github.com/nomic-ai/pyllamacpp

Thanks for your understanding.

**Comment by ParisNeo** [comment]
A new version of the installer fixes this issue.
Please confirm that it works for you and close the issue.

**Comment by zpdg** [comment]
> A new version of the installer fixes this issue. Please confirm that it works for you and close the issue.

I am using Ubuntu. The same error occurs. "./models/gpt4all-lora-quantized-ggml.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74]).......llama_init_from_file: failed to load model"

**Comment by BoQsc** [comment]
Windows 10, Intel, NVIDIA laptop. All recent github clone.
```
llama_model_load: loading model from './models/gpt4all-lora-quantized-ggml.bin' - please wait ...
./models/gpt4all-lora-quantized-ggml.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])
        you most likely need to regenerate your ggml files
        the benefit is you'll get 10-100x faster load times
        see https://github.com/ggerganov/llama.cpp/issues/91
        use convert-pth-to-ggml.py to regenerate from original pth
        use migrate-ggml-2023-03-30-pr613.py if you deleted originals
llama_init_from_file: failed to load model
llama_generate: seed = 1680974915
```

**Comment by ngonzalezromero** [comment]
MacOSx Ventura Intel same error
`llama_model_load: loading model from './models/gpt4all-lora-quantized-ggml.bin' - please wait ...
./models/gpt4all-lora-quantized-ggml.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])
	you most likely need to regenerate your ggml files
	the benefit is you'll get 10-100x faster load times
	see https://github.com/ggerganov/llama.cpp/issues/91
	use convert-pth-to-ggml.py to regenerate from original pth
	use migrate-ggml-2023-03-30-pr613.py if you deleted originals
llama_init_from_file: failed to load model
llama_generate: seed = 1680976601

system_info: n_threads = 8 / 12 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
./run.sh: line 43: 14830 Segmentation fault: 11  python app.py`

**Comment by ParisNeo** [comment]
For people using windows try running install.bat. The script downloads the right model, does the conversion and everything.
The model you download should be converted to the new llama.cpp format.
Take a look at the install.bat code.
I will change the install.sh to do the same.

**Comment by BoQsc** [comment]
Conversion seem to have fix. 
`./models/gpt4all-lora-quantized-ggml.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])`


### Convert.cmd
```
@ECHO OFF
echo Converting the model to the new format
if not exist tmp/llama.cpp git clone https://github.com/ggerganov/llama.cpp.git tmp\llama.cpp
move models\gpt4all-lora-quantized-ggml.bin models\gpt4all-lora-quantized-ggml.bin.original
python tmp\llama.cpp\migrate-ggml-2023-03-30-pr613.py models\gpt4all-lora-quantized-ggml.bin.original models\gpt4all-lora-quantized-ggml.bin
echo The model file (gpt4all-lora-quantized-ggml.bin) has been fixed.

PAUSE
```

**Comment by ngonzalezromero** [comment]
I fixed the error by just adding lines on run.sh fix the error
`
     echo "Converting the model to the new format"
  
  if [ ! -d "tmp/llama.cpp" ]
  then
      git clone https://github.com/ggerganov/llama.cpp.git tmp/llama.cpp
  fi
  
  mv models/gpt4all-lora-quantized-ggml.bin models/gpt4all-lora-quantized-ggml.bin.original
  
  python tmp/llama.cpp/migrate-ggml-2023-03-30-pr613.py models/gpt4all-lora-quantized-ggml.bin.original models/gpt4all-lora-quantized-ggml.bin
`

**Comment by ngonzalezromero** [comment]
happy to create a new PR with this fix
