### ISSUE TITLE
[New UI] install model path differs from used model path

### ISSUE THREAD

**Issue by MarianPalkus** [nomic-ai/gpt4all-ui#180]
## Expected Behaviour
It is possible to install a model via the UI.

## Current Behavior
I am seeing the following error when trying to install a model (e.g. `ggml-nous-gpt4-vicuna-13b.bin`) via the UI:
```
app.py", line 731, in install_model
    with open(installation_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/models/llamacpp/ggml-nous-gpt4-vicuna-13b.bin'
```

## Steps to Reproduce

1. Open the "new UI" and go to "settings"
2. Press "install"-button on any model in the list of models ("Install more models:")

## Possible Solution

Update path in:
https://github.com/nomic-ai/gpt4all-ui/blob/914e2f4d800d0667198bd7d6d93473be0d0a0c40/app.py#L723

and 
https://github.com/nomic-ai/gpt4all-ui/blob/914e2f4d800d0667198bd7d6d93473be0d0a0c40/app.py#L737

to (do we have to drop the leading slash?):
```
Path('models/llama_cpp/') 
```

Accordingly, here:
https://github.com/nomic-ai/gpt4all-ui/blob/914e2f4d800d0667198bd7d6d93473be0d0a0c40/app.py#L710

might be changed to:
```
is_installed = Path(f'models/llama_cpp/{filename}').is_file() 
```

## Context
Please provide any additional context about the issue.

**Comment by ParisNeo** [comment]
The new version corrects this already. I just didn't commit it by then. Sorry guyes.
All will be handled by ui in v3
