### ISSUE TITLE
Ability to download oasst-sft-6-llama-30b by OpenAssistant model

### ISSUE THREAD

**Issue by DavidRLTG** [nomic-ai/gpt4all-ui#193]
## Expected Behavior
It should be available in model downloads

## Current Behavior
It.. isn't!

## Possible Solution
Add a way to download it!

## Context
I know I know I'm dumb for asking, but could we somehow get it, or is it just incompatible? Danke.

**Comment by jadenkiu** [comment]
@DavidRLTG According to the huggingface for the model you are mentioning, they cannot provide the actual model which doesn't work with the model downloads section.
<img width="697" alt="image" src="https://github.com/nomic-ai/gpt4all-ui/assets/58695202/2439a460-88f8-4353-9ad5-8193ae796475">

**Comment by DavidRLTG** [comment]
Aw, what a shame
Well, thanks for your help still, I understand. Have a great day!
