### ISSUE TITLE
Personality is not working

### ISSUE THREAD

**Issue by kdqemre** [nomic-ai/gpt4all-ui#198]
I have installed gpt4allinternetv0 personality tool. this is the exception

Exception in thread Thread-1 (start_message_generation):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kadkoy/Desktop/GPT4ALL-webui/gpt4all-ui/gpt4all_api/api.py", line 666, in start_message_generation
    self.discussion_messages = self.prepare_query(message_id)
  File "/Users/kadkoy/Desktop/GPT4ALL-webui/gpt4all-ui/gpt4all_api/api.py", line 564, in prepare_query
    preprocessed_prompt = self.personality.processor.process_model_input(message["content"])
  File "/Users/kadkoy/Desktop/GPT4ALL-webui/gpt4all-ui/personalities/English/internet/gpt4internetv0/scripts/processor.py", line 118, in process_model_input
    return "### Search engine:\n"+str(self.internet_search(text))+"### Human:\n"+text
  File "/Users/kadkoy/Desktop/GPT4ALL-webui/gpt4all-ui/personalities/English/internet/gpt4internetv0/scripts/processor.py", line 94, in internet_search
    results = extract_results(f"https://duckduckgo.com/?q={query}&t=h_&ia=web", self.personality._processor_cfg["num_results"])
  File "/Users/kadkoy/Desktop/GPT4ALL-webui/gpt4all-ui/personalities/English/internet/gpt4internetv0/scripts/processor.py", line 40, in extract_results
    li_tags = ol_tag.find_all("li")
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by ParisNeo** [comment]
If this is not a problem can you tell me what is the prompt you asked for so that I can test it?

**Comment by kdqemre** [comment]
> If this is not a problem can you tell me what is the prompt you asked for so that I can test it?

I tried several prompt. 
what is the latest discovery of james webb telescope?
Who is the president of USA
What is the result of Turkish presidental elections

Nothing works. Model i am using GPT4ALL  v1.3 groovy. here another exception 

Received message : What is the current Bitcoin price

Searchengine results : 
- Bitcoin (BTC) Price, Real-time Quote & News - Google Finance: Get the latest Bitcoin (BTC / USD) real-time quote, historical performance, charts, and other cryptocurrency information to help you make more informed trading and investment decisions.
https://www.google.com

- Bitcoin Price | BTC Price Index and Live Chart - CoinDesk: Bitcoin Price Index (XBX) Ether Price Index (ETX) Basic Attention Token Price Index (BTX) Cardano Price Index (ADX) Token Governance Bankruptcy Ethereum 2.49 +12.22% Filecoin $ 4.56...
https://www.coindesk.com

- Bitcoin (BTC) Price, Charts, and News | Coinbase: bitcoin price, btc ...: The price of Bitcoin has fallen by 1.12% in the past 7 days. The price increased by 1.07% in the last 24 hours. In just the past hour, the price grew by 0.66%. The current price is $27,295.21 per BTC. Bitcoin is 60.32% below the all time high of $68,789.63. The current circulating supply is 19,376,256 BTC.
https://www.coinbase.com

- Bitcoin price today, BTC to USD live price, marketcap and chart ...: Bitcoin price today, BTC to USD live price, marketcap and chart ...
https://coinmarketcap.com


## Generating message ##
LLModel.generate() got an unexpected keyword argument 'streaming'

## Done ##

**Comment by kdqemre** [comment]
I'm trying different models but nothing works properly. Now i'm getting wrong aswers. I saw you getting proper answers. Please can you explain which models and settings you are using. I have tried wizardLM, GPT4ALL 1.3 groovy . Is there any dependincies for to install Internet personality. i did not figure out what am i missing 

<img width="1126" alt="Ekran Resmi 2023-05
<img width="572" alt="Ekran Resmi 2023-05-19 15 00 37" src="https://github.com/nomic-ai/gpt4all-ui/assets/45230395/5e5c2278-2ac5-4338-92da-8ebc611caf82">
-19 14 57 59" src="https://github.com/nomic-ai/gpt4all-ui/assets/45230395/43163c97-7837-4590-b7df-1f307c5d681a">

**Comment by kdqemre** [comment]
Solution:

If you have driver error in your terminal, install chrome. Any other browsers not working even if chromium based ones.
And update the Pesonality files. On macbook there is compatibility problem for the latest one. Consider this isseu.

**Comment by ParisNeo** [comment]
Hi, sorry for that. You just need to update your gpt4all library:
pip install --upgrade gpt4all
