### ISSUE TITLE
Error installing sentencepiece on Ubuntu 22.04

### ISSUE THREAD

**Issue by mitkox** [nomic-ai/gpt4all-ui#20]
Hey,

I got this error on Ubuntu 22.04 Azure VM. The connectivity in the cloud should be ok. Have you seen this error? 

ch file or directory
        178 | # include <Python.h>
            |           ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentencepiece

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Failed to install required packages. Please check your internet connection and try again.

**Comment by ParisNeo** [comment]
I'll ask for help from the community cuz i don't have a ubuntu pc right now. Thanks for reporting

**Comment by Ulanmax** [comment]
try to run:
```
sudo apt update
sudo apt install -y cmake
sudo apt install -y procps
```

**Comment by crypto-maniac** [comment]
same error  and the last command given by Ulanmax didnt make it
  ```
   compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentencepiece

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Failed to install required packages. Please check your internet connection and try again.

```

**Comment by Ulanmax** [comment]
Also try this command: 
`sudo apt install build-essential`

**Comment by crypto-maniac** [comment]
same output after your last command

`src/sentencepiece/sentencepiece_wrap.cxx:178:11: fatal error: Python.h: No such file or directory
       # include <Python.h>
                 ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentencepiece

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Failed to install required packages. Please check your internet connection and try again.
`

**Comment by JPurrier** [comment]
I'm getting a similar error when using a M2 mac:
 note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentencepiece

**Comment by Ulanmax** [comment]
The reason is sentencepiece has not yet published a wheel for Python 3.11.

**Comment by JPurrier** [comment]
any work around?

**Comment by zodiacg** [comment]
try ``sudo apt install python3.11-dev``

**Comment by crypto-maniac** [comment]
it worked with last command from zodiacg 
`sudo apt install python3.11-dev`

thanks a lot!

**Comment by crypto-maniac** [comment]
well know when i command "./run.sh
i got this output

 

> Checking discussions database...
> Ok
> llama_model_load: loading model from './models/gpt4all-lora-quantized.bin' - please wait ...
> llama_model_load: invalid model file './models/gpt4all-lora-quantized.bin' (too old, regenerate your model files or convert them with convert-unversioned-ggml-to-ggml.py!)
> llama_init_from_file: failed to load model
> llama_generate: seed = 1680971163
> 
> system_info: n_threads = 8 / 4 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
> ./run.sh: line 43:  4278 Segmentation fault      (core dumped) python app.py
>

**Comment by crypto-maniac** [comment]
it is not that i dont like Python ,this language is so powerfull , but for the setup it alway been a nightmare :)

**Comment by Alcsaw** [comment]
It seems that pyllamacpp depends on sentencepiece which still does not support Python 311. See: https://github.com/google/sentencepiece/issues/810

How did you guys managed to make this work on Linux, since the install.sh seems to be broken as of now?

**Comment by ijoukov** [comment]
> try `sudo apt install python3.11-dev`

This worked for me on WSL. Thanks!

**Comment by mitkox** [comment]
sudo apt install python3.11-dev 
solves the problem

**Comment by crypto-maniac** [comment]
Well i still get error as mentioned 

> It seems that pyllamacpp depends on sentencepiece which still does not support Python 311. See: [google/sentencepiece#810](https://github.com/google/sentencepiece/issues/810)
> 
> How did you guys managed to make this work on Linux, since the install.sh seems to be broken as of now?

**Comment by Boxylmer** [comment]
For those running `sudo apt install python3.11-dev` and still getting problems, make sure to remove regular python3.11 and also run `sudo apt install build-essential` beforehand.

**Comment by eerio** [comment]
You should run `sudo apt install python3-dev`. I ran into the same problem while installing `sentencepiece`, and this helped me without needing to specify Python 3 subversion, as in the answers above. I already had `build-essential` installed.
