### ISSUE TITLE
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Nyandaro** [nomic-ai/gpt4all-ui#204]
## Current Behavior

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

This is an error that only occurs for windows users
Especially if you don't have C/C++ build tools

## Steps to Reproduce

1. webui.bat install

## Possible Solution

https://postgresweb.com/python-error-which-is-required-to-install-pyproject-toml-based-projects

https://visualstudio.microsoft.com/en/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

Just download VisualStudioSetup and select C/C++ build tools on the first screen to install

This is a problem on the llama-cpp-python side
I think you probably distributed it without building it.

**Comment by ParisNeo** [comment]
Hi there. The  llama-cpp-python is a library I use but I didn't build it myself.
https://github.com/abetlen/llama-cpp-python

On my PC when I install it it just installs prebuilt wheels so no recompilation is required on my PC.

Meybe I need to ask them to make build for multiple platforms.

Also, with this, you can activate cublas and use your GPU for very fast predictions.

**Comment by ParisNeo** [comment]
yeah it is very complicated as the llamacpp depends heavily on hardware. they provided compiled wheels for only few configurations

**Comment by ParisNeo** [comment]
you still can use just gpt4all backend. Set it as default backend in your configuration file configs/default_local.yaml and look for backend and set it to gpt4all
