### ISSUE TITLE
install win bat file is BROKEN

### ISSUE THREAD

**Issue by cyb3raly** [nomic-ai/gpt4all-ui#26]
simply doesnt work, asks to install python and upon choice it just closes.

python is already installed on my machine yet it still says not detected.

:)

**Comment by SnyderWillCode** [comment]
Possibly python is not found in your Windows environmental variables.

**Comment by ParisNeo** [comment]
Have you checked that your python is in your system Path?
When the installer doesn't find python, it tries to download it from a server. Is the server reachable in your country?
Here is the server the script is trying to download from:
https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe

**Comment by Galaxy1878** [comment]
i swear it's broken, it says i dont have pip but it's false, i tested it already

**Comment by ParisNeo** [comment]
LOL you don't need to swear, i beleive you.
in a cmd console, what happens when you do python? If that doesn't work, then  python is not in your path
If it works, try to do pip to verify tit works.

Finally can you pull the latest version and try again?
