### ISSUE TITLE
Error: llama_model_load: invalid model file './models/gpt4all-lora-quantized.bin' (too old, regenerate your model files or convert them with convert-unversioned-ggml-to-ggml.py!)

### ISSUE THREAD

**Issue by Gero39** [nomic-ai/gpt4all-ui#38]
I installed via install.bat, then downloaded the model from the torrent and moved it to /models/.
End up with this:
![image](https://user-images.githubusercontent.com/75932124/230685519-b2fe6f26-a75a-476b-9701-5f6094248fa1.png)

**Comment by ParisNeo** [comment]
Hi. Last update to install.bat and run.bat should fix the problem.
