### ISSUE TITLE
Error for mac os installation

### ISSUE THREAD

**Issue by ivanlp10n2** [nomic-ai/gpt4all-ui#4]
I tried to run `./install.sh` but I get the following error 

```
Running setup.py install for sentencepiece ... error
  error: subprocess-exited-with-error

  × Running setup.py install for sentencepiece did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      running install
      [...]
      ./build_bundled.sh: line 19: cmake: command not found
      ./build_bundled.sh: line 20: nproc: command not found
      ./build_bundled.sh: line 20: cmake: command not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
```

I checked the mac os installation details but none of the faq solved my issue. I'll be adding it to the docs and create the PR. 

Also I get the following msg: 
```
Downloading latest model
./install.sh: line 100: wget: command not found
Virtual environment created and packages installed successfully.
Every thing is setup. Just run run.sh
```

so I'm going to fix that too

**Comment by CaptainChemist** [comment]
Have you tried using homebrew to install python3.11? That got me through the installation process- my run.sh still fails though (install script downloads gpt4all-lora-quantized-ggml.bin  but doesn't convert it to gpt4all-converted.bin)

**Comment by mkinney** [comment]
Not sure if related, and these are minor but I needed to run: `chmod +x install.sh` and I had change the first line to just `#!bash`.

**Comment by nikeyes** [comment]
Have you tried installing wget with brew, closing the terminal and running the installer again?
`brew install wget`

**Comment by Ulanmax** [comment]
try to run 
```
brew install cmake
brew install coreutils
```

**Comment by ParisNeo** [comment]
Can anyone make a install_macos.sh and test it? You can be inspired by the install.sh code

**Comment by ralyodio** [comment]
can we get a brew package for this? there's one for arch.

**Comment by ParisNeo** [comment]
I am not a specialist in Mac, but if you know how to do it, fork the project, do your wizardry and then do a Pull Request.
