### ISSUE TITLE
Model frozen when prompted something - Windows

### ISSUE THREAD

**Issue by arroyoquiel** [nomic-ai/gpt4all-ui#40]
## OS
Windows 11

## Expected Behavior
When I send the message "List 10 dogs." or anything else, the program should give me a reply.

## Current Behavior
When I send the message "List 10 dogs." or anything else, the program freezes and doesn't reply, this also disallows more messages to be sent.

## Steps to Reproduce

1. Clean git clone, install, run
2. Go to localhost:9600 and send a message
3. Program gets frozen

## Screenshots

![cmd_vEwrBWeYDU](https://user-images.githubusercontent.com/81461845/230707800-c3f5336f-9833-4673-8d33-0e38e53c27e9.png)
![msedge_GZk4XA4hty](https://user-images.githubusercontent.com/81461845/230707802-d6c8c016-77c4-4db7-9d92-bfc7cc1fe5ad.png)

**Comment by ParisNeo** [comment]
So you see nothing in the console? Normally you wait and text starts coming in the console and xhen it is all buffered, it is committed to the ui. I'll test when i get home.

**Comment by ParisNeo** [comment]
Are you sure the model conversion is working fine with your new script ?

**Comment by ParisNeo** [comment]
Can u try converting the model using
pyllamacpp-convert-gpt4all path/to/gpt4all_model.bin path/to/llama_tokenizer path/to/gpt4all-converted.bin

**Comment by arroyoquiel** [comment]
> Are you sure the model conversion is working fine with your new script ?

Yes, the run.bat proceeds with no errors when using the fix inside it.

> Can u try converting the model using pyllamacpp-convert-gpt4all path/to/gpt4all_model.bin path/to/llama_tokenizer path/to/gpt4all-converted.bin

Going to try it now

**Comment by ParisNeo** [comment]
In this case u need to download the gpt4all model first. From their repo. Get a llamaa tokenizer from hugging face then convert. That one worked for me. Can u do a change in the code if it works for you?

**Comment by ParisNeo** [comment]
Try to follow this:
https://github.com/ParisNeo/gpt4all_Tools/blob/main/README.md

**Comment by arroyoquiel** [comment]
> Try to follow this: https://github.com/ParisNeo/gpt4all_Tools/blob/main/README.md

No luck getting it to reply via the UI

**Comment by ParisNeo** [comment]
Ok I'll take it from here. I finally have accessx to a PC :)
