### ISSUE TITLE
Install.bat is broken

### ISSUE THREAD

**Issue by Galaxy1878** [nomic-ai/gpt4all-ui#43]
## Expected Behavior

i expected it to run

## Current Behavior
it gave me an error

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. install gpt4all-ui with git
2. run install bat
3. lock at error

## Context
i have pip in my cmd path nad python too
## Screenshots
![image](https://user-images.githubusercontent.com/103894516/230717658-9f989c35-e8aa-4140-9f67-459609d12dc1.png)

**Comment by ParisNeo** [comment]
I just fixed the error

It was a ( that somehow was turned to ( in the install.bat code

Thank you very much

**Comment by ParisNeo** [comment]
Please confirm that it works for you and close the issue.
Thanks for testing

**Comment by ramzeez88** [comment]
It works now. I had an issue with run.bat yesterday and the model itself. All I did was to uninstall the gpt4all-ui. Download the repo in .zip and replace the files in the gpt4all-ui folder. Run cmd and activate my conda env. Run install.bat and it fixes the model file on the go.

**Comment by vbwyrde** [comment]
FYI - I downloaded with the visual studio option and I do have the issue with the install.bat mentioned earlier.  I will try downloading the zip and replacing the files and see if that works.

**Comment by jasonwynn10** [comment]
Tested and working at present.

**Comment by vbwyrde** [comment]
I downloaded the zip and the install.bat was the same as what was downloaded with the Visual Studio download.  Looking at the bat file it seems the problem is with this line:
if /i ".choice." equ "Y" (

**Comment by ramzeez88** [comment]
i don't know much on windows 11 but do you run it in an environment or directly through windows cmd?

**Comment by vbwyrde** [comment]
I've been tooling around with it to see if I can fix it.  I am running it as a batch file, so I double click it to initiate it.  So far I have not found an answer to why the choice variable is coming in empty.  I'm still working on it.  I tried it on both of my windows machines and I get the same result.   As far as I know this *should* work:

REM Check if pip is installed
set /p="Checking for pip..." <nul
python -m pip >nul 2>&1
if %errorlevel% neq 0 (
    set /p choice=Pip is not installed. Would you like to install pip? [Y/N]
    echo "%choice%"
    if /i "%choice%" equ "Y" (
        REM Download get-pip.py
        echo Downloading get-pip.py...
        powershell -Command "Invoke-WebRequest -Uri 'https://bootstrap.pypa.io/get-pip.py' -OutFile 'tmp/get-pip.py'"
        REM Install pip
        echo Installing pip...
        python tmp/get-pip.py
    ) else (
        echo Please install pip and try again.
        pause
        exit /b 1
    )
) else (
    echo OK
)

However, for some reason when I type Y and enter the     echo "%choice%" shows ""

**Comment by ramzeez88** [comment]
firstly,i would suggest to use a virtual environment , for example with anaconda and choose python ver 3.10.x
secondly, run uninstall.bat just in case it installed anything 
activate the virt env in cmd with conda activate and  type cd your path to where you unzipped the files
then type install.bat

**Comment by Galaxy1878** [comment]
guys I found out the problem, look if you're using more than one version of python
i was using 3.10.6 with pip in his directory so i deleted the 3.11 and it started to work.
