### ISSUE TITLE
Could not download gpt4all-lora-quantized-ggml.bin

### ISSUE THREAD

**Issue by Sicmatr1x** [nomic-ai/gpt4all-ui#46]
I try to download gpt4all-lora-quantized-ggml.bin at https://the-eye.eu/public/AI/models/nomic-ai/gpt4all/gpt4all-lora-quantized-ggml.bin, but the browser show me this error code: ERR_HTTP2_PROTOCOL_ERROR

**Comment by ParisNeo** [comment]
It works for me and for all those who used this. And beleive me those days. I think the problem is on your side.

Some countries may block some websites. Or maybe you have a filewall rule that prevents this or you have a bad configuration . Try another browser to see if this is a brouser issue.

**Comment by vbwyrde** [comment]
I was able to download the bin file, however, I get this error when I execute the run.bat:

llama_model_load: loading model from './models/gpt4all-lora-quantized-ggml.bin' - please wait ...
./models/gpt4all-lora-quantized-ggml.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])

**Comment by ParisNeo** [comment]
It is advised to use the install.bat 

At the end of the script there is a conversion step where we use the lama.cpp code to convert the file.
```
git clone https://github.com/ggerganov/llama.cpp.git tmp\llama.cpp
move models\gpt4all-lora-quantized-ggml.bin models\gpt4all-lora-quantized-ggml.bin.original
python tmp\llama.cpp\migrate-ggml-2023-03-30-pr613.py models\gpt4all-lora-quantized-ggml.bin.original models\gpt4all-lora-quantized-ggml.bin
```

Best regards

**Comment by vbwyrde** [comment]
Ok.  I ran uninstall.bat and then install.bat ... here was the output.  It does appear to have worked, but I thought you might be interested in the errors it mentions.  Note:  I originally downloaded using the Visual Studio option from github.

The default model file (gpt4all-lora-quantized-ggml.bin) already exists. Do you want to replace it? Press B to download it with a browser (faster). [Y,N,B]?B
Link has been opened with the default web browser, make sure to save it into the models folder. When it finishes the download, press any key to continue.
Press any key to continue . . .

Converting the model to the new format
'git' is not recognized as an internal or external command,
operable program or batch file.
        1 file(s) moved.
C:\Users\mabrams\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\Users\\mabrams\\source\\repos\\gpt4all-ui\\tmp\\llama.cpp\\migrate-ggml-2023-03-30-pr613.py': [Errno 2] No such file or directory
The model file (gpt4all-lora-quantized-ggml.bin) has been fixed.
Cleaning tmp folder
Virtual environment created and packages installed successfully.
Every thing is setup. Just run run.bat
Press any key to continue . . .

**Comment by vbwyrde** [comment]
And interestingly, when I execute run.bat, I now get this message:
Ok
Traceback (most recent call last):
  File "C:\....\source\repos\gpt4all-ui\app.py", line 535, in <module>
    bot = Gpt4AllWebUI(app, args)
  File "C:\...\source\repos\gpt4all-ui\app.py", line 205, in __init__
    self.prepare_a_new_chatbot()
  File "C:\...\source\repos\gpt4all-ui\app.py", line 210, in prepare_a_new_chatbot
    self.chatbot_bindings = self.create_chatbot()
  File "C:\...\source\repos\gpt4all-ui\app.py", line 216, in create_chatbot
    return Model(
  File "C:\...\source\repos\gpt4all-ui\env\lib\site-packages\pyllamacpp\model.py", line 54, in __init__
    raise Exception(f"File {ggml_model} not found!")
Exception: File ./models/gpt4all-lora-quantized-ggml.bin not found!

**Comment by ParisNeo** [comment]
oops
it looks like you have no git installed on your pc and that's why it is not working.

Thanks for the information. I'll add this to the installer.

You may start by installing git before running install.bat for the meanwhile.

**Comment by vbwyrde** [comment]
Ok, just an FYI - between the several things I needed to do 1) get the install.bat to use "%choice%" instead of ".choice." 2) install python, 3) install git, run the uninstall.bat and then the install.bat ... now the command prompt that starts up when clicking run.bat is working.  However, it does peg my CPU at 100% and is moving very very slowly.  I can get to the web interface which looks reasonably good.  However the interaction is extremely slow.  I'm on a Windows 11 machine with this hardware:   Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz 3.19 GHz and Installed RAM 15.9 GB
 
 As I very much agree with the intention of this project I will be happy to help however I can.   Thanks for doing this.  It's incredibly important work, imo, and very much appreciated.

**Comment by ParisNeo** [comment]
you're welcome. I really did this for the community. I'm not paid to do it. I do it on my free time. So if others want to help, please grub one of the issues I did set and if you follow the rules it would be eazy to contribute.
