### ISSUE TITLE
Unable to run other models - e.g. Vicuna 7b

### ISSUE THREAD

**Issue by CyberProto** [nomic-ai/gpt4all-ui#50]
First of all: Thank you for this web-ui tool! It is awesome. 

## Expected Behavior
Load different model - Vicuna 7b

## Current Behavior
Model does not load. Get error: [2023-04-08 12:52:17,856] {app.py:1744} ERROR - Exception on /update_model_params [POST]

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. Place vicuna 7b .bin in the models folder
2. Run run.bat
3. change model to vicuna 7b file
4. click update parameters button
5. Model doesnt load; error comes back; default model used

**Comment by ParisNeo** [comment]
This is under testing. Can you give me the link to the model you are testing?

**Comment by CyberProto** [comment]
I was using the one linked on the nomic-ai/gpt4all page
https://huggingface.co/eachadea/ggml-vicuna-7b-4bit/tree/main

using rev1.

**Comment by ParisNeo** [comment]
I am working on this.
Ok, I'll do a pull request as soon as i finish.

**Comment by CyberProto** [comment]
Thank you! Much appreciated.

**Comment by ParisNeo** [comment]
Now you can select a model from the list

**Comment by CyberProto** [comment]
It works! Thank you!

**Comment by ParisNeo** [comment]
you're welcome
