### ISSUE TITLE
Installation on Windows machine aborts during step: 'Do you want to download and install the GPT4All model? [Y/N]'

### ISSUE THREAD

**Issue by DigitalRonin3000** [nomic-ai/gpt4all-ui#52]
## Expected Behavior
Trying to install GPT4ALL on a Windows 10 machine using 'install.bat' file.

## Current Behavior
During installation with 'install.bat' during the step: 'Do you want to download and install the GPT4All model? [Y/N]'
an error is given and the installation aborts.

## Steps to Reproduce

1. Run 'install.bat'.
2. Download the latest 'gpt4all-lora-quantized-ggml.bin' file. Then the step is presented 'Do you want to download and install the GPT4All model? [Y/N]'
3. Press 'Y' or 'N'. In both cases the same message is shown: '-v was unexpected at this time.' and the installation is aborted.

## Screenshots
![image](https://user-images.githubusercontent.com/130251335/230741569-7b28ec2e-37de-44cf-af3a-862f6a8f6753.png)

**Comment by ramzeez88** [comment]
this might be case sensitive so N instead of n

**Comment by DigitalRonin3000** [comment]
Unfortunately it wasn't the case sensitive Y/N choice. I just tried both Y and N in capital letters and I get the same error. 

See the screenshots below.

![image](https://user-images.githubusercontent.com/130251335/230748539-301c6808-2831-42ba-85c4-510f19269aad.png)
![image](https://user-images.githubusercontent.com/130251335/230748555-f2efffe3-e307-493d-a2f4-b061443f2b2e.png)

**Comment by jadenkiu** [comment]
I'm experiencing the same issue with the install.bat. When I try to run just the run.bat after downloading the gpt4-lora-quantized.ggml.bin from the earlier step, there is this error:
`llama_model_load: loading model from './models/gpt4all-lora-quantized-ggml.bin' - please wait ...
./models/gpt4all-lora-quantized-ggml.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])
        you most likely need to regenerate your ggml files
        the benefit is you'll get 10-100x faster load times
        see https://github.com/ggerganov/llama.cpp/issues/91
        use convert-pth-to-ggml.py to regenerate from original pth
        use migrate-ggml-2023-03-30-pr613.py if you deleted originals
llama_init_from_file: failed to load model
llama_generate: seed = 1681005830

system_info: n_threads = 8 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |`, a search of the error leads me to this post: [https://github.com/ggerganov/llama.cpp/issues/655](url) but I have not figured out how it can be used to resolve the issue with the install.bat and run.bat.

**Comment by jadenkiu** [comment]
Seems like the error will also affect install.bat, there is some code under the part about -v that seems to address converting the .bin file, though the install.bat just ends after "Do you want to download and install the GPT4ALL model? [Y/N]".

<img width="733" alt="image" src="https://user-images.githubusercontent.com/58695202/230750728-b93bce0d-b638-4f17-b371-2c61374a02df.png">
