### ISSUE TITLE
run.sh: line 43: 79546 Illegal instruction     (core dumped) python app.py

### ISSUE THREAD

**Issue by ItzChr1s1** [nomic-ai/gpt4all-ui#55]
## Expected Behavior
It seems like I have installed everything successfully but when I start run.sh. It is unable to start.

## Current Behavior
**"run.sh: line 43: 79546 Illegal instruction     (core dumped) python app.py"**

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. I started with https://github.com/nomic-ai/gpt4all-ui instructions of git clone and install

2. I received an error and went to an issue that already had it https://github.com/nomic-ai/gpt4all-ui/issues/20 and ran "sudo apt install python3.11-dev" which worked.

3. I then went here and followed the instructions: https://github.com/nomic-ai/gpt4all-ui/blob/main/docs/Linux_Osx_Install.md
and sucessfully installed and told me to run.sh

4. Now when I use bash run.sh I receive the line 43: 79546 error above.

## Screenshots
<img width="632" alt="Screenshot 2023-04-08 at 5 18 39 PM" src="https://user-images.githubusercontent.com/49334413/230742940-82483b32-621e-4bf1-bb59-fa31697e8970.png">

**Comment by sadalsvvd** [comment]
Saw this same issue trying to help a friend get set up. They had a 2020 M1.

**Comment by ItzChr1s1** [comment]
> Saw this same issue trying to help a friend get set up. They had a 2020 M1.

hm I'm running ProxMox and using an Ubuntu VM to set it up but it is on a 2017 imac too

**Comment by yzimmermann** [comment]
I get
`run.sh: line 43:  7657 Segmentation fault      (core dumped) python app.py`
on Ubuntu 22.04 also after running `sudo apt install python3.11-dev` for the installation.

**Comment by crypto-maniac** [comment]
same for me , there is library problem with python 3.11

**Comment by ItzChr1s1** [comment]
I created a new Ubuntu VM, went through the process and ended in the exact same error message rip. 

I attempted the docker setup instead it successfully built but when trying to run it kind of just stops with this message (I do have gpt4all-lora-quantized-ggml.bin inside the models folder):
`gpt4all-ui_webui_1 exited with code 132`

<img width="570" alt="Screenshot 2023-04-09 at 5 24 20 PM" src="https://user-images.githubusercontent.com/49334413/230797245-ec741a2b-b0eb-4625-9908-828fe5ff4ac9.png">

**Comment by tljoy** [comment]
I'm getting the segmentation fault error @yzimmermann mentioned. 

My logs show the following, in case the additional detail is helpful:

`Apr  9 20:34:03 localhost kernel: python[15729]: segfault at 14d0 ip 00007f75cf6824f3 sp 00007f75ce69bd10 error 4 in _pyllamacpp.cpython-311-x86_64-linux-gnu.so[7f75cf676000+62000]
Apr  9 20:34:03 localhost kernel: Code: 54 f1 10 48 8d 7c 24 28 4c 89 f9 48 8b 70 08 e8 03 3e ff ff 48 8b 7c 24 28 4c 8b 2b ba 07 69 0f c7 48 8b 77 e8 e8 1d 4d ff ff <4d> 8b 45 08 31 d2 49 89 c1 49 f7 f0 49 8b 45 00 48 8b 04 d0 49 89
Apr  9 20:34:03 localhost systemd[1]: Started Process Core Dump (PID 15730/UID 0).
Apr  9 20:34:04 localhost systemd-coredump[15731]: Resource limits disable core dumping for process 15727 (python).
Apr  9 20:34:04 localhost systemd-coredump[15731]: Process 15727 (python) of user 0 dumped core.
Apr  9 20:34:04 localhost systemd[1]: systemd-coredump@6-15730-0.service: Succeeded.`

**Comment by andzejsp** [comment]
I got `run.sh: line 43: 21412 Illegal instruction python app.py` after running `bash run.sh`.

I also installed python 3.11.1 on debian 11

Im also trying to run this on proxmox VM debian 11

**Comment by fvillena** [comment]
> I created a new Ubuntu VM, went through the process and ended in the exact same error message rip.
> 
> I attempted the docker setup instead it successfully built but when trying to run it kind of just stops with this message (I do have gpt4all-lora-quantized-ggml.bin inside the models folder): `gpt4all-ui_webui_1 exited with code 132`
> 
> <img alt="Screenshot 2023-04-09 at 5 24 20 PM" width="570" src="https://user-images.githubusercontent.com/49334413/230797245-ec741a2b-b0eb-4625-9908-828fe5ff4ac9.png">

Similar problem here. The container starts but after i ask something to the bot, the container exits with error code 139

**Comment by andzejsp** [comment]
Well its not exactly similar to what im having. I have no idea how to make it run in debian. Still getting illegal instruction when trying to launch python app.py.

**Comment by andzejsp** [comment]
I can confirm that this error persists in ubuntu 22.04.2 aswell:

![image](https://user-images.githubusercontent.com/80409979/231467103-112c69a1-059b-4a4e-a84d-d328d7dfe726.png)
![image](https://user-images.githubusercontent.com/80409979/231467208-ee8b20fd-942f-42b7-9cbb-9e6cbe31fa78.png)

Sorry for posting images, im running this on proxmox and not set up ssh just yet.

**Comment by andzejsp** [comment]
Debugging this more, i started commenting out imports from app.py. 
When i comment out pyllamacpp (line 29) in app.py i get some error. 

Yes i know, commenting out code blocks will give errors. But everything else gave me the same illegal instruction.
![image](https://user-images.githubusercontent.com/80409979/231489286-5114f272-f914-4a2b-a1b5-e272648277d8.png)

So my hunch is that that import has something to do with not being able to run on Ubuntu/debian in VM

**Comment by ParisNeo** [comment]
It seems like a pyllamacpp bug. Please report it on their repo.

**Comment by andzejsp** [comment]
Actually it was CPU fault, the VM didnt have, i guess, the right instruction set so it was illegal. I switched CPU to use host CPU (in proxmox GUI) and now im getting to the web page. But got error that model is bad. 

The windows installation asks to convert the model after it downloads it, but the linux install.3.10.sh script does not.

**Comment by ParisNeo** [comment]
I was checking the scripts written by the community to install the models and for macos and linux, they miss the conversion step. So I'm actually upgrading the scripts to make them do the conversion. unfortunately I'm doing this blindly and these days, all focus is on backend so I am litterally working alone on this project right now. I need feedback from the community.
When I finish coding the script, i'll tell you, you test and report any problems and I think we'll fix it together if you want.

**Comment by ItzChr1s1** [comment]
> I was checking the scripts written by the community to install the models and for macos and linux, they miss the conversion step. So I'm actually upgrading the scripts to make them do the conversion. unfortunately I'm doing this blindly and these days, all focus is on backend so I am litterally working alone on this project right now. I need feedback from the community. When I finish coding the script, i'll tell you, you test and report any problems and I think we'll fix it together if you want.

no worries man. it looks like i'm not alone on the issue, but regardless you're doing great. One step closer! 👍
