### ISSUE TITLE
Install.sh not working properly because the Python.h library 

### ISSUE THREAD

**Issue by RaevschiCatalin** [nomic-ai/gpt4all-ui#56]
fatal error: Python.h: No such file or directory
        178 | # include <Python.h>
            |           ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentencepiece

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Failed to install required packages. Please check your internet connection and try again.

**Comment by rodrigolopezguerra** [comment]
You can check on the detailed instructions of the script to find the issue actually [here]([here](https://github.com/nomic-ai/gpt4all-ui/blob/main/docs/Linux_Osx_Install.md)).

Just in case try

```
brew update
brew upgrade
```

and remember to update .zshrc if the case and requiered

**Comment by crypto-maniac** [comment]
check here if you still related problem
#8958677581 #
