### ISSUE TITLE
Windows install script error message

### ISSUE THREAD

**Issue by rexzhang360** [nomic-ai/gpt4all-ui#6]
Checking for python...OK
Checking for pip...OK
Checking for venv...OK
Creating virtual environment ...OK
Activating virtual environment ...OK
Installing requirements ...
Requirement already satisfied: pip in c:\windows\system32\env\lib\site-packages (23.0.1)
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Failed to install required packages. Please check your internet connection and try again.
Press any key to continue . . .
------------------------------------------------------------------------------
where is venv folder?

**Comment by rexzhang360** [comment]
got it work, after copy requirements.txt from folder into C:\Windows\System32\env\Lib\site-packages\pip-23.0.1.dist-info

**Comment by vard88508** [comment]
same issue but solution above did not help

**Comment by ParisNeo** [comment]
That seams odd. Resuirements.txt exists in the base folder. Are you sure you are executing the indtall script from the right folder?

**Comment by arroyoquiel** [comment]
Should be fixed now, seems like run.bat is the one giving trouble now.
