### ISSUE TITLE
error log attempted to install as user and system using admin cmd bat and normal cmd

### ISSUE THREAD

**Issue by nekohacker591** [nomic-ai/gpt4all-ui#60]
D:\AI\gpt4all\GPT4ALL-WEBUI\gpt4all-ui>pip install --user pyllamacpp
Collecting pyllamacpp
  Using cached pyllamacpp-1.0.6-cp311-cp311-win_amd64.whl (191 kB)
Collecting streamlit
  Using cached streamlit-1.21.0-py2.py3-none-any.whl (9.7 MB)
Collecting streamlit-ace
  Using cached streamlit_ace-0.1.1-py3-none-any.whl (3.6 MB)
Collecting sentencepiece
  Using cached sentencepiece-0.1.97.tar.gz (524 kB)
  Preparing metadata (setup.py) ... done
Collecting torch
  Using cached torch-2.0.0-cp311-cp311-win_amd64.whl (172.3 MB)
Collecting altair<5,>=3.2.0
  Using cached altair-4.2.2-py3-none-any.whl (813 kB)
Collecting blinker>=1.0.0
  Using cached blinker-1.6.1-py3-none-any.whl (13 kB)
Requirement already satisfied: cachetools>=4.0 in c:\users\micha\appdata\roaming\python\python311\site-packages (from streamlit->pyllamacpp) (5.3.0)
Requirement already satisfied: click>=7.0 in c:\python311\lib\site-packages (from streamlit->pyllamacpp) (8.1.3)
Collecting importlib-metadata>=1.4
  Using cached importlib_metadata-6.2.1-py3-none-any.whl (21 kB)
Requirement already satisfied: numpy in c:\python311\lib\site-packages (from streamlit->pyllamacpp) (1.24.2)
Requirement already satisfied: packaging>=14.1 in c:\users\micha\appdata\roaming\python\python311\site-packages (from streamlit->pyllamacpp) (23.0)
Collecting pandas<2,>=0.25
  Using cached pandas-1.5.3-cp311-cp311-win_amd64.whl (10.3 MB)
Requirement already satisfied: pillow>=6.2.0 in c:\python311\lib\site-packages (from streamlit->pyllamacpp) (9.4.0)
Collecting protobuf<4,>=3.12
  Using cached protobuf-3.20.3-py2.py3-none-any.whl (162 kB)
Requirement already satisfied: pyarrow>=4.0 in c:\python311\lib\site-packages (from streamlit->pyllamacpp) (11.0.0)
Collecting pympler>=0.9
  Using cached Pympler-1.0.1-py3-none-any.whl (164 kB)
Requirement already satisfied: python-dateutil in c:\python311\lib\site-packages (from streamlit->pyllamacpp) (2.8.2)
Requirement already satisfied: requests>=2.4 in c:\users\micha\appdata\roaming\python\python311\site-packages (from streamlit->pyllamacpp) (2.28.2)
Requirement already satisfied: rich>=10.11.0 in c:\users\micha\appdata\roaming\python\python311\site-packages (from streamlit->pyllamacpp) (13.3.3)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: typing-extensions>=3.10.0.0 in c:\python311\lib\site-packages (from streamlit->pyllamacpp) (4.5.0)
Collecting tzlocal>=1.1
  Using cached tzlocal-4.3-py3-none-any.whl (20 kB)
Collecting validators>=0.2
  Using cached validators-0.20.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Collecting gitpython!=3.1.19
  Using cached GitPython-3.1.31-py3-none-any.whl (184 kB)
Collecting pydeck>=0.1.dev5
  Using cached pydeck-0.8.0-py2.py3-none-any.whl (4.7 MB)
Collecting tornado>=6.0.3
  Using cached tornado-6.2-cp37-abi3-win_amd64.whl (425 kB)
Collecting watchdog
  Using cached watchdog-3.0.0-py3-none-win_amd64.whl (82 kB)
Requirement already satisfied: filelock in c:\python311\lib\site-packages (from torch->pyllamacpp) (3.9.0)
Collecting sympy
  Using cached sympy-1.11.1-py3-none-any.whl (6.5 MB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Requirement already satisfied: jinja2 in c:\python311\lib\site-packages (from torch->pyllamacpp) (3.1.2)
Collecting entrypoints
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting jsonschema>=3.0
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Collecting toolz
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Requirement already satisfied: colorama in c:\users\micha\appdata\roaming\python\python311\site-packages (from click>=7.0->streamlit->pyllamacpp) (0.4.6)
Collecting gitdb<5,>=4.0.1
  Using cached gitdb-4.0.10-py3-none-any.whl (62 kB)
Collecting zipp>=0.5
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting pytz>=2020.1
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python311\lib\site-packages (from jinja2->torch->pyllamacpp) (2.1.2)
Requirement already satisfied: six>=1.5 in c:\users\micha\appdata\roaming\python\python311\site-packages (from python-dateutil->streamlit->pyllamacpp) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\micha\appdata\roaming\python\python311\site-packages (from requests>=2.4->streamlit->pyllamacpp) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\micha\appdata\roaming\python\python311\site-packages (from requests>=2.4->streamlit->pyllamacpp) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\micha\appdata\roaming\python\python311\site-packages (from requests>=2.4->streamlit->pyllamacpp) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\micha\appdata\roaming\python\python311\site-packages (from requests>=2.4->streamlit->pyllamacpp) (2022.12.7)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\micha\appdata\roaming\python\python311\site-packages (from rich>=10.11.0->streamlit->pyllamacpp) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\micha\appdata\roaming\python\python311\site-packages (from rich>=10.11.0->streamlit->pyllamacpp) (2.14.0)
Collecting pytz-deprecation-shim
  Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting tzdata
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting decorator>=3.4.0
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting smmap<6,>=3.0.1
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
Requirement already satisfied: attrs>=17.4.0 in c:\users\micha\appdata\roaming\python\python311\site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit->pyllamacpp) (22.2.0)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.19.3-cp311-cp311-win_amd64.whl (62 kB)
Requirement already satisfied: mdurl~=0.1 in c:\users\micha\appdata\roaming\python\python311\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->streamlit->pyllamacpp) (0.1.2)
Installing collected packages: sentencepiece, pytz, mpmath, zipp, watchdog, tzdata, tornado, toolz, toml, sympy, smmap, pyrsistent, pympler, protobuf, networkx, entrypoints, decorator, blinker, validators, torch, pytz-deprecation-shim, pydeck, pandas, jsonschema, importlib-metadata, gitdb, tzlocal, gitpython, altair, streamlit, streamlit-ace, pyllamacpp
  DEPRECATION: sentencepiece is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for sentencepiece ... error
  error: subprocess-exited-with-error

  × Running setup.py install for sentencepiece did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      running install
      c:\python311\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\sentencepiece
      copying src\sentencepiece/__init__.py -> build\lib.win-amd64-cpython-311\sentencepiece
      copying src\sentencepiece/_version.py -> build\lib.win-amd64-cpython-311\sentencepiece
      copying src\sentencepiece/sentencepiece_model_pb2.py -> build\lib.win-amd64-cpython-311\sentencepiece
      copying src\sentencepiece/sentencepiece_pb2.py -> build\lib.win-amd64-cpython-311\sentencepiece
      running build_ext
      building 'sentencepiece._sentencepiece' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\src
      creating build\temp.win-amd64-cpython-311\Release\src\sentencepiece
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Python311\include -IC:\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" /EHsc /Tpsrc/sentencepiece/sentencepiece_wrap.cxx /Fobuild\temp.win-amd64-cpython-311\Release\src/sentencepiece/sentencepiece_wrap.obj /std:c++17 /MT /I..\build\root\include
      cl : Command line warning D9025 : overriding '/MD' with '/MT'
      cl : Command line warning D9002 : ignoring unknown option '/std:c++17'
      sentencepiece_wrap.cxx
      src/sentencepiece/sentencepiece_wrap.cxx(2822): fatal error C1083: Cannot open include file: 'sentencepiece_processor.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentencepiece

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

D:\AI\gpt4all\GPT4ALL-WEBUI\gpt4all-ui>app.py
Traceback (most recent call last):
  File "D:\AI\gpt4all\GPT4ALL-WEBUI\gpt4all-ui\app.py", line 18, in <module>
    from pyllamacpp.model import Model
ModuleNotFoundError: No module named 'pyllamacpp'

**Comment by arroyoquiel** [comment]
Sentencepiece is not officially supported for python 3.11, you need python 3.10

**Comment by koltregaskes** [comment]
I'm also gettning this error.  I had 311 already installed so I installed 39, tried install.bat again but still get the above error.  What am I doing wrong?
