### ISSUE TITLE
invalid model file

### ISSUE THREAD

**Issue by NQevxvEtg** [nomic-ai/gpt4all-ui#62]
## Expected Behavior
Just works

## Current Behavior
The model file might be corrupted... Downloaded many times, also tried different browsers. 

## Steps to Reproduce
Create a new chat

```
[2023-04-09 23:48:55,297] {_internal.py:224} INFO - 127.0.0.1 - - [09/Apr/2023 23:48:55] "GET /new_discussion?title=test HTTP/1.1" 200 -
llama_model_load: loading model from './models/gpt4all-lora-quantized-ggml.bin' - please wait ...
./models/gpt4all-lora-quantized-ggml.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])
	you most likely need to regenerate your ggml files
	the benefit is you'll get 10-100x faster load times
	see https://github.com/ggerganov/llama.cpp/issues/91
	use convert-pth-to-ggml.py to regenerate from original pth
	use migrate-ggml-2023-03-30-pr613.py if you deleted originals
llama_init_from_file: failed to load model
./run.sh: line 43: 44097 Segmentation fault      (core dumped) python app.py
```

**Comment by zjpiazza** [comment]
Same issue here when running via docker compose. I have downloaded the bin file from different sources as well, each gives the same result. Not sure if being on Windows machine would cause this?

```
((gpt4all-ui) ) PS C:\Users\zjpia\code\gpt4all-ui> docker compose up
[+] Running 1/0       
 - Container gpt4all-ui-webui-1  Created                                                                                                 0.0s
Attaching to gpt4all-ui-webui-1
gpt4all-ui-webui-1  | llama_model_load: loading model from './models/gpt4all-lora-unfiltered-quantized.bin' - please wait ...
gpt4all-ui-webui-1  | llama_model_load: invalid model file './models/gpt4all-lora-unfiltered-quantized.bin' (too old, regenerate your model files or convert them with convert-unversioned-ggml-to-ggml.py!)
gpt4all-ui-webui-1  | llama_init_from_file: failed to load model
gpt4all-ui-webui-1  | llama_generate: seed = 1681111211
gpt4all-ui-webui-1  | 
gpt4all-ui-webui-1  | system_info: n_threads = 8 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
gpt4all-ui-webui-1 exited with code 139
```

**Comment by rchaput** [comment]
You must use the [migrate-ggml-2023-03-30-pr613.py](https://github.com/ggerganov/llama.cpp/blob/master/migrate-ggml-2023-03-30-pr613.py) script to convert the "old" model (`-ggml`) to the "new" format (`-ggjt`).
This is independent of the OS, and is caused by a recent update from a dependency of gpt4all (llama.cpp).

1. Download the script from GitHub, place it in the gpt4all-ui folder.
2. Run `python migrate-ggml-2023-03-30-pr613.py models/gpt4all-lora-quantized-ggml.bin models/gpt4all-lora-quantized-ggjt.bin`.
3. Finally, you must run the app with the new model, using `python app.py --model gpt4all-lora-quantized-ggjt.bin` (update your `run.sh` or `run.bat` accordingly if you use them instead of directly running `python app.py`).

Source: https://github.com/ggerganov/llama.cpp/issues/662
(Note that the original answer mentions another script, `convert-gpt4all-to-ggml`, this was unnecessary for me as the download model was already in the `ggml` format)

**Comment by zjpiazza** [comment]
> You must use the [migrate-ggml-2023-03-30-pr613.py](https://github.com/ggerganov/llama.cpp/blob/master/migrate-ggml-2023-03-30-pr613.py) script to convert the "old" model (`-ggml`) to the "new" format (`-ggjt`). This is independent of the OS, and is caused by a recent update from a dependency of gpt4all (llama.cpp).
> 
> 1. Download the script from GitHub, place it in the gpt4all-ui folder.
> 2. Run `python migrate-ggml-2023-03-30-pr613.py models/gpt4all-lora-quantized-ggml.bin models/gpt4all-lora-quantized-ggjt.bin`.
> 3. Finally, you must run the app with the new model, using `python app.py --model gpt4all-lora-quantized-ggjt.bin` (update your `run.sh` or `run.bat` accordingly if you use them instead of directly running `python app.py`).
> 
> Source: [ggerganov/llama.cpp#662](https://github.com/ggerganov/llama.cpp/issues/662) (Note that the original answer mentions another script, `convert-gpt4all-to-ggml`, this was unnecessary for me as the download model was already in the `ggml` format)

Will test this out and give it a try. Appreciate you <3

**Comment by andzejsp** [comment]
> I wasn't able to get gpt4all-lora-unfiltered-quantized.bin converted per these instructions. Where you able to @zjpiazza ?

if you are on windows, just use the official repo instructions. Yesterday i had no problems on windows .

**Comment by zjpiazza** [comment]
> > I wasn't able to get gpt4all-lora-unfiltered-quantized.bin converted per these instructions. Where you able to @zjpiazza ?
> 
> if you are on windows, just use the official repo instructions. Yesterday i had no problems on windows .

When I tried using the Flask application directly, it said platform not supported or something to that effect.

**Comment by navyfighter12** [comment]
> > I wasn't able to get gpt4all-lora-unfiltered-quantized.bin converted per these instructions. Where you able to @zjpiazza ?
> 
> if you are on windows, just use the official repo instructions. Yesterday i had no problems on windows .

I was able to get the unfiltered configured however when using the webui it is not acting as unfiltered. 
It is refusing to do things that normally works in the shell based script for gpt4all when using unfiltered. It also responds for me as the user telling the bot that its inappropriate and to stop lol 

If I ask it tell me a joke it the bot tries but the "user" responds not funny automatically. Its got a mind of its own and responds for me. Super weird

**Comment by ParisNeo** [comment]
didn't test the uncensored version. But the UI contains an extra conditionning to ensure that the model doesn't do bad stuff. Maybe this is screening the uncensored stuff.
This is a all users system so by default we want to protect users from any bad behavior. But in next version we will give the advanced users the possibility to control the conditionning. But we're not responsible for what people does with this.
We promote freedom, but we don't endorse bad use.

**Comment by navyfighter12** [comment]
Checking to see if this has been implemented yet

**Comment by andzejsp** [comment]
i dont think it is.. not sure cuz i dont play with this much, just coding other stuff :D, so stay tuned

**Comment by ParisNeo** [comment]
As I said, change the personality if you don't want it to behave as the default AI. Our default conditionning will restrict the AI from doing anything deemed bad. But, if you want, you can create another personality file and do what you want at your own risk.

**Comment by navyfighter12** [comment]
> As I said, change the personality if you don't want it to behave as the default AI. Our default conditionning will restrict the AI from doing anything deemed bad. But, if you want, you can create another personality file and do what you want at your own risk.

That's fine and all but yu said in next version we will give the advanced users the possibility to control the conditioning. That's what I was asking about. I can create another personality file instead, just not convenient
