### ISSUE TITLE
ImportError: DLL Load failed  while importing _pylammacpp: The specified module could not be found

### ISSUE THREAD

**Issue by taaha** [nomic-ai/gpt4all-ui#65]
![image](https://user-images.githubusercontent.com/5251294/230940457-b6911bc9-236a-4d30-847f-499f3210ad41.png)

Getting above error when I type run.bat. Any ideas on how to fix this?

**Comment by ParisNeo** [comment]
Hi there have you installed the tool using install.bat?
It is supposed to install the pyllamacpp library.

**Comment by taaha** [comment]
Yes I have run install.bat. pylammacpp is also present in my env\lib\site-packages
![image](https://user-images.githubusercontent.com/5251294/230986708-bbc99399-adea-4fe3-84fa-6fff1eff8666.png)

**Comment by ParisNeo** [comment]
This is odd. it seems to be an issue in pyllamacpp module. You can post an issue on their repository here:
https://github.com/nomic-ai/pyllamacpp
