### ISSUE TITLE
ggml-vicuna-13b-4bit-rev1 problem

### ISSUE THREAD

**Issue by andzejsp** [nomic-ai/gpt4all-ui#67]
Something wrong with this model?
![image](https://user-images.githubusercontent.com/80409979/230977912-5aa43014-5518-4401-bb75-be1d2a099110.png)

**Comment by andzejsp** [comment]
i did conver the model just now and tired to do it again and now it just cuts out mid prompt
![image](https://user-images.githubusercontent.com/80409979/230978858-77805986-380b-416f-87a8-d4d3fe9951c3.png)

**Comment by ParisNeo** [comment]
hi and thanks for trying to test the ui.
I think it may have something to do with the end character. In GPT4All model, it is /f I don't know how vicuna does. I hon't have a good enough connection these days to download the model as I am on vacation. But I'll try to think of a solution.

Bare in mind that there are new updates to the python bindings that will roll out soon and would make the model way more eazy to use. We're working on it.
I also see that you are using an outdated version of the UI. Please upgrade it and try again.

Best regards

**Comment by andzejsp** [comment]
thanks, keep working on this :D its awsome. maybe you and your team could look into creating matrix server for these types of discussions for people to share what works, and tips and tricks? right now im like a blind man at an orgy.. im feeling things out.

**Comment by ParisNeo** [comment]
I was planning on doing this :)

**Comment by macronomicus** [comment]
Im testing this same model now myself, seems to work on the latest build, although im hitting the token limit again which was fixed recently for the standard model we use here.
