### ISSUE TITLE
[Docker] can't boot up: gpt4all-ui_webui_1 exited with code 132

### ISSUE THREAD

**Issue by Anyvie** [nomic-ai/gpt4all-ui#69]
## Expected Behavior
Project is starting, or at least some info in logs

## Current Behavior
```
debian@host:~/dockers/gpt4all-ui$ docker-compose up
Recreating gpt4all-ui_webui_1 ... done
Attaching to gpt4all-ui_webui_1
gpt4all-ui_webui_1 exited with code 132
```

## Steps to Reproduce
git clone
docker-compose build --no-cache
docker-compose up

## Context
Tried this on a dedicated server at OVH (Debian 11.6)

If it helps : 
`docker-compose build --no-cache` : [docker-compose_build.txt](https://github.com/nomic-ai/gpt4all-ui/files/11199715/docker-compose_build.txt)
`docker-compose --verbose up` : [docker-compose_verbose_up.txt](https://github.com/nomic-ai/gpt4all-ui/files/11199714/docker-compose_verbose_up.txt)
`cat /proc/cpuinfo` : [cat_proc-cpuinfo.txt](https://github.com/nomic-ai/gpt4all-ui/files/11199716/cat_proc-cpuinfo.txt)

EDIT:
`docker compose build && docker compose up` (without the hyphen) does the same.
`docker -v` : Docker version 23.0.3, build 3e7cbfd

**Comment by andzejsp** [comment]
what does the container logs say?

**Comment by Anyvie** [comment]
```
debian@host:~/dockers/gpt4all-ui$ docker compose logs
debian@host:~/dockers/gpt4all-ui$ docker-compose logs
Attaching to gpt4all-ui-webui-1
debian@host:~/dockers/gpt4all-ui$ 
```

I don't have any logs, that's why I tried the verbose option, but I can't find the trouble :/

**Comment by ParisNeo** [comment]
Guys, If you want, you can contribute. 
If you find  solutions to the docker problems that did work for you :
- Fork the project
- Do your updates
- Test them
- Do a pull request
- I'll review it and if it is fine, I'll accept it

So far I have accepted all contributions. They are all valuable.
Thanks for your help.

**Comment by XanderStrike** [comment]
I am getting this too. I have [ggjt-model.bin](https://huggingface.co/LLukas22/gpt4all-lora-quantized-ggjt/blob/main/ggjt-model.bin) in my models folder.

The container process emits no log lines. `restart: always` causes it to restart a couple times but does not produce any further logs (which is expected).

Exit code 132 usually means an illegal instruction. The machine I'm trying to run this on has an Intel CPU and no GPU. Is there anything precompiled in this that might expect a GPU or non-Intel CPU?

**Comment by jWXZSCsqrpZRSVwauBjn** [comment]
This isn't a docker specific Problem. 
The underlying problem behind code 132 is 

`run.sh: line 43: 1420737 Illegal instruction     (core dumped) python app.py`

I'm running on a Ubuntu 20.04 Server with an x86 Intel CPU without a GPU

**Comment by jWXZSCsqrpZRSVwauBjn** [comment]
This isn't a docker specific Problem. 
The underlying problem behind code 132 is 

`run.sh: line 43: 1420737 Illegal instruction     (core dumped) python app.py`

I'm running on a Ubuntu 20.04 Server with an x86 Intel CPU without a GPU

Edit: This exact bahivor is also described in #55

**Comment by r1ksk1** [comment]
I have a feeling this is to do with the CPU not supporting AVX2 (So basically it probably an older processor).

Try on a machine that supports AVX2 and see if you got a win, like I did.

Good Luck!
