### ISSUE TITLE
 table message has no column named type

### ISSUE THREAD

**Issue by HenkDz** [nomic-ai/gpt4all-ui#71]
It used to run fine, but after Yesterday's updates I get this.
`Checking discussions database...
llama_model_load: loading model from './models/gpt4all-lora-quantized-ggml.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 4096
llama_model_load: n_embd  = 4096
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 32
llama_model_load: n_layer = 32
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 11008
llama_model_load: n_parts = 1
llama_model_load: type    = 1
llama_model_load: ggml map size = 4017.70 MB
llama_model_load: ggml ctx size =  81.25 KB
llama_model_load: mem required  = 5809.78 MB (+ 2052.00 MB per state)
llama_model_load: loading tensors from './models/gpt4all-lora-quantized-ggml.bin'
llama_model_load: model size =  4017.27 MB / num tensors = 291
llama_init_from_file: kv self size  = 4096.00 MB
Traceback (most recent call last):
  File "E:\gpt4all-ui\app.py", line 468, in <module>
    bot = Gpt4AllWebUI(app, args)
  File "E:\gpt4all-ui\app.py", line 98, in __init__
    self.prepare_a_new_chatbot()
  File "E:\gpt4all-ui\app.py", line 114, in prepare_a_new_chatbot
    self.condition_chatbot()
  File "E:\gpt4all-ui\app.py", line 135, in condition_chatbot
    message_id = self.current_discussion.add_message(
  File "E:\gpt4all-ui\db.py", line 200, in add_message
    message_id = self.discussions_db.insert(
  File "E:\gpt4all-ui\db.py", line 112, in insert
    cursor = conn.execute(query, params)
sqlite3.OperationalError: table message has no column named type`

**Comment by macronomicus** [comment]
I had a similar issue when updating from some of the earlier code too yesterday, what I did was uninstall & delete everything but the models, then reinstall fresh.  We found other bugs yesterday on fresh installs, but it was fixed already, so fresh install should be good to go. One thing to keep in mind, they're working on the python bindings which will substantially speed things up.

I would say there might be a fix for your error, but given how fast this is developing it may not happen, since a fresh install is quick, most of the env should be cached in your system so install should be really fast, especially since you already have model too.

**Comment by ParisNeo** [comment]
hi everyone. This is due to the update of the database format. A fast fix is rename your database.db file. The model will build a new database with the new format.

Sorry for the invconvenience. We have now a versionning system, so next upgrades will just automatically upgrade your database.

**Comment by keekychen** [comment]
sqlite3.ProgrammingError: Error binding parameter 1: type 'Discussion' is not supported - after renamed database.db

Traceback (most recent call last):
  File "/mnt/g/wsl/gpt4all-ui/app.py", line 504, in <module>
    bot = Gpt4AllWebUI(app, config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/wsl/gpt4all-ui/app.py", line 122, in __init__
    self.prepare_a_new_chatbot()
  File "/mnt/g/wsl/gpt4all-ui/app.py", line 138, in prepare_a_new_chatbot
    self.condition_chatbot()
  File "/mnt/g/wsl/gpt4all-ui/app.py", line 154, in condition_chatbot
    if self.db.does_last_discussion_have_messages():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/wsl/gpt4all-ui/db.py", line 165, in does_last_discussion_have_messages
    last_message = self.select("SELECT * FROM message WHERE discussion_id=?", (last_discussion_id,), fetch_all=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/wsl/gpt4all-ui/db.py", line 86, in select
    cursor = conn.execute(query, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: Error binding parameter 1: type 'Discussion' is not supported
