### ISSUE TITLE
docker file missing config?

### ISSUE THREAD

**Issue by sgehrman** [nomic-ai/gpt4all-ui#75]
## Expected Behavior
docker doesn't run

## Current Behavior

Got errors, I had to add
COPY ./config.py /srv/config.py
COPY ./configs /srv/configs

to the dockerfile to run

## Steps to Reproduce
 
try to run the docker compose version on linux

## Possible Solution

add to docker file
COPY ./config.py /srv/config.py
COPY ./configs /srv/configs

## Context
 linux

## Screenshots
If applicable, add screenshots to help explain the issue.

**Comment by ParisNeo** [comment]
I have changed the docker script to add the configs directory to the container. Can you please pull and try again?

**Comment by ParisNeo** [comment]
Sorry again. I have updated the docker files:
I added configs and personalities dir as well as copyed the config.py file.
