### ISSUE TITLE
Proxypass using Nginx proxy manager

### ISSUE THREAD

**Issue by andzejsp** [nomic-ai/gpt4all-ui#76]
I have run the `app.py with --host 0.0.0.0` and can access the web ui from local machines, but when i try to proxypass  and access it from domain, it shows in the console that the  "GET / HTTP/1.1" 200 -  but the web page is not loading. I mean its loading forever, but i cant access it. 

All it shows is this.

![image](https://user-images.githubusercontent.com/80409979/231670559-a263791a-1988-4f3f-acd0-908c2d64d41a.png)

My proxy custom settings are:

```
location /gpt4all/ {
		rewrite ^/gpt4all(/.*)$ /$1 break;
		proxy_pass http://192.168.0.210:9600;
		proxy_http_version 1.1;
		auth_basic "Authorization required";
		auth_basic_user_file /data/access/1;
		proxy_set_header Authorization "";
		proxy_set_header Connection "";
	}
```

For other sites this setup is working, here i dont know why its not.

I tried enabling websocket support, but that didnt help
Im by no means an expert in nginx, All  my knowledge comes from googling around for solutions, given if i ask the right questions :)

Any help would be appreciated.

**Comment by ParisNeo** [comment]
Can you try with the latest version?

**Comment by andzejsp** [comment]
Still not working, i think its my fault, because i have no idea or understanding on how to proxypass with a sub path.

like i want example.com/gpt4all/ to proxy into local http://192.168.0.210:9600/ 

But it seems that the page loads but the assets are still trying to pull from base url wich is example.com and not example.com/gpt4all/
I removed the real domain from picture for safety.
![image](https://user-images.githubusercontent.com/80409979/231746990-b471ba0e-2e89-4a7a-9b76-d26a09bcf45d.png)

**Comment by ParisNeo** [comment]
I am sorry for that. I don't have much experience with proxies.
If you find a solution or if someone from the community can help, feel free to post your solution.

Thnx

**Comment by zodiacg** [comment]
Unless the proxied app explicitly states it supports running from a sub path, don't proxypass it with a sub path. Prefix stripping is not enough. 

As you already noticed, normally frontend developers use '/'-starting uris to pull the resources the root path. If sub path needs to be supported, the frontend part will need a revamp to add a configurable path name before every resource uri.

**Comment by andzejsp** [comment]
That is what i was afraid of, thank you for explaining.
