### ISSUE TITLE
Exits without feedback / Cannot load _pyllamacpp

### ISSUE THREAD

**Issue by J0J0HA** [nomic-ai/gpt4all-ui#84]
## Current Behavior
If I run the ``run.bat``, I get nothing but the logo. By inspecting the ``run.bat``-file, I saw i was in the ``pause > nul`` and the execution of the ``app.py`` had already finished.  
By running ``app.py`` manually, it also just exited without doing anything.
By **proffesional** ``print``-debugging (irony), I was able to trace the error back to be in the ``_pyllamacpp.cp311-win_amd64.pyd``, as you can see from the attached screenshots.

## Context
* Windows 10 / build 10.0.19045
* x64-Architecture
* RAM is either 8GB or 16GB; I could not find it, but it is probably 16GB. 
* Tell me to add anything required.

## Screenshots
Modified code:
![grafik](https://user-images.githubusercontent.com/80523427/232119048-2a5e93b9-84b5-4ff6-aaa1-8f0b6f9200f5.png)
![grafik](https://user-images.githubusercontent.com/80523427/232119092-590c396e-5fda-43c0-8732-37809666ab33.png)
Result:
![grafik](https://user-images.githubusercontent.com/80523427/232119637-4e0c301f-8015-4527-a009-9ac790b7360c.png)

**Comment by andzejsp** [comment]
What is your CPU?

If it does not support AVX2 instruction set then youre out of luck

**Comment by GrandArth** [comment]
Having a similar problem here, mine have proper output:
```python
Traceback (most recent call last):
  File "D:\Users\x\Documents\gpt4all-ui\app.py", line 33, in <module>
    from pyGpt4All.api import GPT4AllAPI
  File "D:\Users\x\Documents\gpt4all-ui\pyGpt4All\api.py", line 14, in <module>
    from pyllamacpp.model import Model
  File "D:\Users\x\Documents\gpt4all-ui\env\lib\site-packages\pyllamacpp\model.py", line 21, in <module>
    import _pyllamacpp as pp
ModuleNotFoundError: No module named '_pyllamacpp'
```
