### ISSUE TITLE
Enhance renaming discussions ui

### ISSUE THREAD

**Issue by ParisNeo** [nomic-ai/gpt4all-ui#9]
Hi there. I have built the rename discussion in a hurry. Can someone please change the aesthetics to make it fit with the overall theme?
Thnx

**Comment by vamsikrishna71** [comment]
assign this issue to me, i can do.

**Comment by jadenkiu** [comment]
@ParisNeo I think this can be closed, it already looks good in dark and light mode now.
<img width="302" alt="image" src="https://user-images.githubusercontent.com/58695202/233910042-12b391af-3429-4d3d-b423-68caac92bc4d.png">
<img width="288" alt="image" src="https://user-images.githubusercontent.com/58695202/233910056-ae8a06b7-ec58-4c7b-9178-0885c9a6a6dd.png">
