### ISSUE TITLE
Segmentation Fault ; app.py --> No Answer

### ISSUE THREAD

**Issue by doctorerre** [nomic-ai/gpt4all-ui#93]
## Expected Behavior
Expecting answer from the UI at localhost:9600 but getting image attached

## Current Behavior
No Answer at all

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. Install
2. Run
3. Talk to bot

## Possible Solution
Maybe doing some arrange in app.py cause is a segmentation fault

## Context

UI showing well, app running with no problem at UBUNTU but not behaving as a chatbot

## Screenshots
Scrennshot attached.
![imageui11](https://user-images.githubusercontent.com/79534115/232371926-89d87e61-df11-4c3c-b4f4-ee4b580144ad.jpg)
![image12ui](https://user-images.githubusercontent.com/79534115/232371957-c26ef95a-c9cd-4f5b-bcbd-418f166c5158.jpg)

**Comment by michal0000000** [comment]
Did you figure this out?
